import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Intro from "../components/Intro";
import Sections from "../components/Sections";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Crypto P2P</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Intro />
        <Sections />
      </main>
      <Footer />
    </>
  );
};

export default Home;
