import type { NextPage } from "next";
import Head from "next/head";
import Section from "../components/Section";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Intro from "../components/Intro";
import Tabs, { TabsVertical } from "../components/Tabs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="">
        <Intro />
        <Section
          type="blue"
          sectionId="features"
          headerText="Everything you need to exchange your tokens."
          subheaderText="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        >
          <Tabs />
        </Section>
        <Section
          type="white"
          sectionId="about"
          headerText="Simplify everyday token operations."
          subheaderText="Etiam eu dui pulvinar, pharetra odio."
        >
          <TabsVertical />
        </Section>
        <Section
          type="blue"
          sectionId="getstarted"
          headerText="Get started today."
          subheaderText="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
        />
        <Section
          type="white"
          sectionId="faqs"
          headerText="Frequently asked questions."
          subheaderText="If you can’t find what you’re looking for, email our support team and if you’re lucky someone will get back to you."
        />
      </main>
      <Footer />
    </>
  );
};

export default Home;
